-   hosts: openshift-dev
    become: true
    roles:
        -   docker

    tasks:
        -   name: download openshift components
            unarchive:
                src:  https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
                dest: /usr/local/bin/
                remote_src: yes
                extra_opts: [--strip-components=1]

        -   name: install python kubernetes and openshift tools
            pip:
                name: kubernetes, openshift
                state: latest

        -   name: deploy openshift cluster
            command: oc cluster up

        -   name: create openshift project
            k8s:
                state: present
                inline:
                    kind: ProjectRequest
                    metadata:
                        name: hello-from-ansible
                    displayName: Ansible Test Project
                    description: This project was created using Ansible