---
# docker installation tasks

-   name: upgrade and update APT
    apt:
        upgrade: yes
        update_cache: yes

-   name: install needed system components
    apt:
        name:
            -   apt-transport-https
            -   ca-certificates
            -   curl
            -   gnupg-agent
            -   net-tools
            -   software-properties-common
            -   python3-pip
            -   virtualenv
            -   python3-setuptools
        state: latest

-   name: add docker official GPG key
    apt_key:
        keyserver: https://download.docker.com/linux/ubuntu/gpg
        id: 7EA0A9C3F273FCD8
        state: present

-   name: check docker APT key has not been altered
    command: apt-key fingerprint 0EBFCD88
    register: fingerprint_check
    changed_when: False
    failed_when: "'9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88' not in fingerprint_check.stdout"

-   name: add docker repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

-   name: install docker
    apt:
        name:
            -   docker-ce
            -   docker-ce-cli
            -   containerd.io
        state: latest
        update_cache: yes

-   name: install docker module for python
    pip:
        name: docker

-   name: setup docker insecure registry
    copy:
        src: "{{ role_path }}/files/daemon.json"
        dest: /etc/docker/
    notify: restart docker
